# Linear models 2: ANOVA's and Posthoc Tests

If the explanatory variable is categorical data, you can still fit a linear model.
In that case you are fitting average values for each group.
It's called a One-way ANOVA.
In contrast to an independent t-test, you can compare more than two groups.

The hypothesis you test with an ANOVA is if there are any differences between the groups.
If you are interested in which group differ from each other, you have to apply an extra test, called a posthoc test.


## ANOVA in R

Like linear regression, you use the `lm()` function to fit a the statistical model, and the function `anova()` to test the hypothesis.
NB: make sure that R interprets the explanatory variable as categorical. 
The easiest is that you use letters in the group category names.

In your data map you find the file koeien.xlsx.
It is about milking speed (in kg/min) for three different cattle breeds.


```{excercise koeien}
Milk production

* Write a script that imports the data set
* Add code that a) fit the linear model and b) run an ANOVA
* Check the output and write down, as comment, your conclusions

```


## Posthoc tests

If you find a significant difference between the groups, you can test which groups are different with a posthoc test.

Over time, many different posthoc tests have been developed, with sometimes subtle differences in assumptions and optimal use. 
To keep life simple, we stick with three posthoc tests for three different situations:

* If groups sizes are similar, choose **Tukey HSD**
* If group sizes are not similar, choose **Bonferroni**
* If you only want to compare the groups with a control group (instead of all possible pairwise comparisons), choose **Dunnet's**

Like the enormous variety of posthoc test, are there also many ways to apply a posthoc test in R.
The package **emmeans** has the function `emmeans()` that works for almost all possible statistical situations, therefor it is high recommendend to use this function.

The function `emmeans()` requires as first argument the output of a statistical model (in our case the output of `lm()`).
Both Tukey HSD and Bonferroni make a pairwise comparison for each combination of groups.
In the function `emmeans()` you can define that with the argument `specs = pairwise  ~ explvar`, where explvar is the name of the explanatory variable you want to test.
The default posthoc test is Tukey HSD. 
If you want a Bonferroni instead, add the argument adjust = "bonf".


```{excercise, posthoc}
Posthoc test

* Test, with the right test, which cattle breeds differ in milking speed.
* Look at the output, and make your conclusions. Write them down as comment in your script.

```


The result of `emmeans()` is build up in two sections:

* The first section (emmeans) show the average effect of each category, with confidence interval. For applied science is maybe more important than the question which groups are significant different! The name for these average effects are the Estimated Marginal Means.
* The second section (contrasts) show the hypothesis test of each pairwise comparison, the actual posthoc test. Look at the p-value in the last column.


### Dunnet's

For Dunnet's Posthoc test you need to use for *spects* not pairwise, but `trt.vs.ctrl` (treatment versus control): `specs = trt.vs.ctrl ~ explvar`

The function automatically takes the first category (lowest in alphabet) as control.
With the argument `ref=i` you can define which category is the control, with for i the index number of the control category (place all categories in alphabetic orde, a use the position of the control.

In case the control is the last in the row, you can also use: `specs = tr.vs.ctrlk ~ explvar`.


## Practice

The next excercise is based on research, published in  the *American Society of Animal Science*.

The  spore element silicium (Si) has a positive influence on the bone quality.
In the reserarch they were focused on the question if Si supplements in lactating mares influences the blood si levels in the foals.
They tested three doses (A, B and C), with 5 replicates, in total 15 mares:

| dosis   | Si-gehalte ($\mu$g/l)    |
| :-----: | :--------------------: |
|   A     | 129; 137; 129; 134; 139  |
|   B     | 133; 148; 142; 139; 134  |
|   C     | 138; 148; 140; 145; 148  |


```{exercise, Silicium}
Silicium

* Make an Excel file wit the data
* Make an R script that imports the data, create an appropriate graph, apply an One-way ANOVA and in applicable the right Posthoc test.
* write down you conclusions as comment in the script.

```

## Two-way ANOVA's

Up to now we have only focussed on one explanatory variable.
But often your experiment is more complex.
E.g. you are testing the growth effect of a new fertilizer on tomato's, and are you testing it on three different tomato varieties.
Now you have two factors that could influence the growth of the plants: fertilizer and variety.

Luckily we can add both them easily in a linear model: `growth ~ fertilizer + variety`.


```{exercise, twoway}
Two-way anova

* Write code that import the dataset plantengroei.xlsx from your data map.
* Make an approriate graph.
* Test if fertilizer and/or plant variaty has an effect on growth rate.
* Write down your conclusions as a comment.

```


## Main and  interaction effects

In the previous example we have used a `+` to add an extra explanatory effects.
That plus means that the next variable has an effect, independend from the previous one.
In this case you are testing the **main** effects of each variable.
If you also want to include possible **interaction** effects you need to use a `*`.


## Posthoc tests for two-way ANOVAs

The function `emmeans()` can be used for two-way ANOVAs as well.
You can either test for one of the explanatory variables or all combinations of both.
In that case you write `specs = pairwise ~ var1:var2`, with for var1 and var2 both explanatory variables.


## Practice

R contains data sets to practice. 
One of them is about the effect of vitamin C on tooth growth in *Cavia porcellus*.
With the function `data("ToothGrowth)` you create an object of that dataset.

The vitamin was applied in three doses (0.5, 1 and 2 mg/day) (*dose*) in two different types of supplement (orange juice or vitamin C extrat) (*supp*).
The length of the odontoplasts (growth cells in the teeth) were measured.

```{exercise, cavia}
Tooth growth

* make an object of the data set ToothGrowth
* check the structure of the data set

```

As you can see, the column dose has numerical values.
If you are going to put that column as explanatory variable in an `lm()` function, the function will treat it as covariate (meaning as a linear regression).
The solution is to make R clear that it is a categorical data.
The function for that is `factor()`: 

```{r}
ToothGrowth$dose <- factor(ToothGrowth$dose)
```

```{exercise cavia_vervolg}
Cavia 2

* apply above function
* make an clear figure with ggplot
* Test both for dose and supp, including interaction for significant effects
* apply an appropriate posthoc test)


```
Tip: with the `table(TootGrowth$dose, TootGrowth$supp)`you can get an overview of the number of replicates.


```{exercise, be}
Fertilation2

You find in your data map the de map staat in de datafolder het bestand bemesting.xlsx.
Het gaat over een bemestingsproef.
De proef bestaat uit twee factoren:
* wel/niet bemest
* wel/niet toevoeging van Kalium/Magnesium/Calcium (afhankelijk van je dataset)

Maak een script die de volgende zaken uitvoert:
  
* importeer de dataset
* maak een figuur die de data goed weergeeft (bedenk zelf hoe je zulke data mooi kan weergeven)
* Stel de hypotheses op voor mogelijke effecten (we houden GEEN rekening met mogelijke interacties)
* Voer een ANOVA uit


```



